# Generated by Django 5.2.1 on 2025-06-06 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartellaClinica',
            fields=[
                ('id_cartella', models.AutoField(primary_key=True, serialize=False)),
                ('data_apertura', models.DateField(null=True)),
                ('note', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Esame',
            fields=[
                ('id_esame', models.AutoField(primary_key=True, serialize=False)),
                ('nome_esame', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Personale',
            fields=[
                ('id_personale', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('data_nascita', models.DateField()),
                ('ruolo', models.CharField(max_length=100)),
                ('specializzazione', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('codice_sede', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('via', models.CharField(max_length=100)),
                ('città', models.CharField(max_length=100)),
                ('CAP', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Paziente',
            fields=[
                ('id_paziente', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('data_nascita', models.DateField()),
                ('codice_fiscale', models.CharField(max_length=16, unique=True)),
                ('sesso', models.CharField(max_length=1)),
                ('id_cartella_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pazienti', to='CentroMedico.cartellaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id_prenotazione', models.AutoField(primary_key=True, serialize=False)),
                ('data_prenotazione', models.DateField()),
                ('id_paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to='CentroMedico.paziente')),
            ],
        ),
        migrations.CreateModel(
            name='VisitaMedica',
            fields=[
                ('codice_visita', models.AutoField(primary_key=True, serialize=False)),
                ('data_visita', models.DateField()),
                ('codice_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visite_mediche', to='CentroMedico.sede')),
                ('id_cartella_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visite_mediche', to='CentroMedico.cartellaclinica')),
                ('id_prenotazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visite_mediche', to='CentroMedico.prenotazione')),
            ],
        ),
        migrations.CreateModel(
            name='Prestazione',
            fields=[
                ('id_prestazione', models.AutoField(primary_key=True, serialize=False)),
                ('data_prestazione', models.DateField()),
                ('referto', models.TextField(null=True)),
                ('id_esame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestazioni', to='CentroMedico.esame')),
                ('codice_visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestazioni', to='CentroMedico.visitamedica')),
            ],
        ),
        migrations.CreateModel(
            name='Fattura',
            fields=[
                ('numero_fattura', models.AutoField(primary_key=True, serialize=False)),
                ('data_emissione', models.DateField()),
                ('importo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatture', to='CentroMedico.paziente')),
                ('codice_visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatture', to='CentroMedico.visitamedica')),
            ],
        ),
        migrations.CreateModel(
            name='ListaEsami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_esame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to='CentroMedico.esame')),
                ('id_prenotazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esami', to='CentroMedico.prenotazione')),
            ],
            options={
                'unique_together': {('id_prenotazione', 'id_esame')},
            },
        ),
        migrations.CreateModel(
            name='PersonalePrestazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_personale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestazioni', to='CentroMedico.personale')),
                ('id_prestazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personale', to='CentroMedico.prestazione')),
            ],
            options={
                'unique_together': {('id_personale', 'id_prestazione')},
            },
        ),
    ]
