# Generated by Django 5.2.1 on 2025-06-26 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentroMedico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paziente',
            name='id_cartella_clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pazienti', to='CentroMedico.cartellaclinica'),
        ),
    ]
