# Generated by Django 5.2.1 on 2025-07-01 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentroMedico', '0002_alter_paziente_id_cartella_clinica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitamedica',
            name='codice_sede',
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='codice_sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to='CentroMedico.sede'),
        ),
    ]
