# Generated by Django 5.2.1 on 2025-07-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentroMedico', '0003_remove_visitamedica_codice_sede_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esame',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
