# Generated by Django 5.2.1 on 2025-07-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentroMedico', '0004_esame_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitamedica',
            name='data_visita',
            field=models.DateField(blank=True, null=True),
        ),
    ]
