# Generated by Django 5.2.1 on 2025-07-03 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentroMedico', '0005_alter_visitamedica_data_visita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitamedica',
            name='id_cartella_clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visite_mediche', to='CentroMedico.cartellaclinica'),
        ),
    ]
