# Generated by Django 5.2.1 on 2025-07-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentroMedico', '0006_alter_visitamedica_id_cartella_clinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestazione',
            name='data_prestazione',
            field=models.DateField(blank=True, null=True),
        ),
    ]
