# Generated by Django 5.2.1 on 2025-07-04 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentroMedico', '0007_alter_prestazione_data_prestazione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenotazione',
            name='codice_sede',
        ),
        migrations.AddField(
            model_name='visitamedica',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CentroMedico.sede'),
        ),
    ]
