# Generated by Django 5.2.1 on 2025-07-04 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentroMedico', '0008_remove_prenotazione_codice_sede_visitamedica_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fattura',
            name='codice_visita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fattura', to='CentroMedico.visitamedica'),
        ),
        migrations.AlterField(
            model_name='visitamedica',
            name='id_prenotazione',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visita_medica', to='CentroMedico.prenotazione'),
        ),
    ]
