# Generated by Django 5.2.1 on 2025-07-04 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentroMedico', '0009_alter_fattura_codice_visita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitamedica',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vede', to='CentroMedico.sede'),
        ),
    ]
