# Generated by Django 5.2.1 on 2025-07-08 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentroMedico', '0011_alter_visitamedica_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paziente',
            name='id_cartella_clinica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paziente', to='CentroMedico.cartellaclinica'),
        ),
    ]
